In [35]:
import numpy as np
X = np.array([[1],[4],[3]])
y_pred = np.array([[3],[2]])
y_actl = np.array([[2],[1]])
lr = 1
W = np.array([1,1])
a = X.shape[0] 
b = X.shape[1] + 1
feat = np.ones((a, b))
feat[:,:-1] = X
feat.transpose()
diff = y_pred - y_actl
slope = np.matmul(feat.transpose(), diff) / (y_pred.shape[0])
W = W - lr * slope
W


ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [42]:
feat = np.ones(X.shape)
print(X*X)
param = 2
for i in range(param):
    #print(i)
    
    feat = np.insert(feat, [0], X**(i), axis=1)
feat


[[ 1]
 [16]
 [ 9]]


array([[ 1.,  1.,  1.],
       [ 4.,  1.,  1.],
       [ 3.,  1.,  1.]])

In [47]:

feat = np.ones(X.shape)
for i in range(1):
    feat = np.insert(feat, [-1], np.sin(X*(1+i)), axis=1)
    feat = np.insert(feat, [-1], np.cos(X*(1+i)), axis=1)
feat

array([[ 0.84147098,  0.54030231,  1.        ],
       [-0.7568025 , -0.65364362,  1.        ],
       [ 0.14112001, -0.9899925 ,  1.        ]])